version: "3"
services:
    nginx:
        image: nginx:1.15
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - webhook_api
        ports:
            - 8081:80
        networks:
            - backend
    webhook_api:
        build: ./php-fpm
        volumes:
            - ../webhook:/var/www/html
        networks:
            - backend
    webhook_worker:
        build: ./php-worker
        volumes:
            - ../webhook:/var/www/html
        environment:
            - APP_WORKDIR=/var/www/html
        networks:
            - backend
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=123123
        volumes:
            - ../data/mysql:/var/lib/mysql
        networks:
            - backend
    adminer:
        image: adminer:latest
        ports:
            - 8080:8080
        networks:
            - backend
networks:
    backend:
